version: '3.7'

services:
  balticlsc-node:
    hostname: balticlsc-node
    image: balticlsc/balticlsc-node:local
    ports:
      - 7000:7000
      - 7001:7001
    networks:
      balticlsc-node:
        aliases:
          - balticlsc-node
          - balticlsc-node.balticlsc-node
      #balticlsc-batch-manager:
      #  aliases:
      #    - balticlsc-node
      #    - balticlsc-node.balticlsc-batch-manager
      #    - balticlsc-batch-manager
      #    - balticlsc-batch-manager.balticlsc-batch-manager
    environment:
      masterHost: balticlsc-server
      masterPort: 5001
      nodePort: 7001
      clusterProxyUrl: https://cluster-proxy:6001
      clusterProjectName: balticlsc
      #batchManagerUrl: https://balticlsc-batch-manager
      batchManagerUrl: https://balticlsc-node
    volumes:
      - type: bind
        source: ./logs/balticlsc-node
        target: /app/logs

  cluster-proxy-swarm:
    hostname: cluster-proxy
    image: balticlsc/balticlsc-cluster-proxy-swarm:local
    networks:
      balticlsc-node:
        aliases:
         - cluster-proxy
         - cluster-proxy.balticlsc-node
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - type: bind
        source: ./logs/cluster-proxy-swarm
        target: /app/logs
    environment:
      projectPrefix: balticlsc
      batchManagerNetworkName: batch-manager
      

networks:
  balticlsc-node:
    external: true
  #balticlsc-batch-manager:
  #  external: true
