version: '3.7'

services:
  tmp-ftpserver:
    image: stilliard/pure-ftpd
    hostname: tmp-ftpserver
    ports:
      - "20:20"
      - "21:21"
      - "30000-30009:30000-30009"
    networks:
      balticlsc-node:
        aliases:
          - tmp-ftpserver
          - tmp-ftpserver.balticlsc-node
    environment:
      PUBLICHOST: tmp-ftpserver
      FTP_USER_NAME: someuser
      FTP_USER_PASS: somepass
      FTP_USER_HOME: /home/ftpdata
    volumes:
      - "./ftp_data:/home/ftpdata:rw"

  tmp-mongodb:
    image: mongo:4.2.3-bionic
    hostname: tmp-mongodb
    ports:
      - '27017-27019:27017-27019'
    networks:
      balticlsc-node:
        aliases:
          - tmp-mongodb
          - tmp-mongodb.balticlsc-node
    environment:
      MONGO_INITDB_DATABASE: images
      MONGO_INITDB_ROOT_USERNAME: someuser
      MONGO_INITDB_ROOT_PASSWORD: somepass

  tmp-mongo-express:
    image: mongo-express
    hostname: tmp-mongo-express
    ports:
      - 8081:8081
    networks:
      balticlsc-node:
        aliases:
          - tmp-mongo-express
          - tmp-mongo-express.balticlsc-node
    environment:
      ME_CONFIG_MONGODB_SERVER: tmp-mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: someuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: somepass

networks:
  balticlsc-node:
    external: true
