version: '3.7'

services:
  balticlsc-front:
    hostname: balticlsc-front
    image: balticlsc/balticfrontend:latest
    ports:
      - 8080:8080
    environment:
      VUE_APP_SERVER_URL: "localhost:8080"
      VUE_APP_REAL_SERVER_URL: "https://host.docker.internal:5001"
