version: '3.7'
services:
  consul:
    hostname: consul
    image: consul
    command: ["agent", "-dev", "-enable-local-script-checks", "-config-file=/etc/consul.json", "-config-dir=/etc/consul.d"]   
    ports:
      - 8400:8400
      - 8500:8500
      - 8502:8502
      - 8600:53
    networks:
      - baltic
    volumes:
      - consul:/consul/data
    configs:
      - source: consul_postgresql
        target: /etc/consul.d/postgresql.json
      - source: consul_json
        target: /etc/consul.json
  fabio:
    hostname: fabio
    image: fabiolb/fabio
    environment:
      - FABIO_REGISTRY_CONSUL_ADDR=consul:8500
      - FABIO_REGISTRY_CONSUL_REGISTER_ADDR=fabio:9998
    networks:
      - baltic
    ports:
      - 9998:9998
      - 9999:9999
    depends_on:
      - consul
  rabbitmq:
    hostname: rabbit
    image: rabbitmq:latest
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - baltic
    depends_on:
      - consul
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    configs:
      - source: enabled_plugins
        target: /etc/rabbitmq/enabled_plugins
      - source: rabbitmq_conf
        target: /etc/rabbitmq/rabbitmq.conf
#  vault:
#    hostname: vault
#    image: vault   
#    ports:
#      - 8200:8200
#    command: ["server", "-config=/etc/vault.json"]
#    environment:
#      - VAULT_ADDR=vault:8200
#      - CONSUL_HTTP_ADDR=consul:8500
#    networks:
#      - baltic
#    depends_on:
#      - consul
#    configs:
#      - source: vault_conf
#        target: /etc/vault.json 
  postgresql:
    hostname: postgresql
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Pa$$w0rd}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    depends_on:
      - consul 
    ports:
      - "5432:5432"
    networks:
      - baltic
  pgadmin:
    hostname: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-Pa$$w0rd}
#    volumes:
#      - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - baltic
    depends_on:
      - postgresql
configs:
  enabled_plugins:
    file: ./conf/rabbitmq/enabled_plugins
  rabbitmq_conf:
    file: ./conf/rabbitmq/rabbitmq.conf
  consul_postgresql:
    file: ./conf/consul/postgresql.json
  consul_json:
    file: ./conf/consul/consul.json
#  vault_conf:
#    file: ./conf/vault/vault.json
    
networks:
  baltic:
    name: baltic
volumes:
  postgres:
    driver: local
  pgadmin:
    driver: local
  rabbitmq:
    driver: local
  consul:
    driver: local
    
