CREATE TABLE IF NOT EXISTS Users (
    Id SERIAL PRIMARY KEY NOT NULL,
    Username VARCHAR(40) NOT NULL,
    Password VARCHAR(72) NOT NULL,
    EmailAddress VARCHAR(128),
    Status INTEGER,
    Stamp TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS UserExtension (
    Id SERIAL PRIMARY KEY NOT NULL,
    UserID INTEGER REFERENCES Users(Id) ON DELETE CASCADE,
    FullName VARCHAR(32),
    RoleInOrganisation VARCHAR(32),
    Phone VARCHAR(24),
    Address VARCHAR(64),
    Country VARCHAR(32),
    Language VARCHAR(32),
    Stamp TIMESTAMPTZ NOT NULL DEFAULT NOW()                                         
);

CREATE TABLE IF NOT EXISTS UserPreferences (
    Id SERIAL PRIMARY KEY NOT NULL,
    UserID INTEGER REFERENCES Users(Id) ON DELETE CASCADE,
    Param VARCHAR(32),
    Value VARCHAR(128),
    Stamp TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS UserRoles (
    Id SERIAL PRIMARY KEY NOT NULL,
    UserID INTEGER REFERENCES Users(Id) ON DELETE CASCADE,
    Role INTEGER NOT NULL,
    Stamp TIMESTAMPTZ NOT NULL DEFAULT NOW()    
);

CREATE TABLE IF NOT EXISTS Session (
    Id SERIAL PRIMARY KEY NOT NULL,
    UserID INTEGER REFERENCES Users(Id) ON DELETE CASCADE,
    SID VARCHAR(32),
    JTI VARCHAR(32),
    Stamp TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS SessionParams (
    Id SERIAL PRIMARY KEY NOT NULL,    
    SessionID INTEGER REFERENCES Session(Id) ON DELETE CASCADE,
    Param VARCHAR(32),
    Value VARCHAR(128),
    Stamp TIMESTAMPTZ NOT NULL DEFAULT NOW()    
);

CREATE TABLE IF NOT EXISTS Company (
    Id SERIAL PRIMARY KEY NOT NULL,
    Name VARCHAR(64),
    IsSupplier BOOLEAN,
    Details VARCHAR(128),
    Stamp TIMESTAMPTZ NOT NULL DEFAULT NOW()              
);

CREATE TABLE IF NOT EXISTS UsersInCompany (
    Id SERIAL PRIMARY KEY NOT NULL,
    UserID INTEGER REFERENCES Users(Id) ON DELETE CASCADE,
    CompanyID INTEGER REFERENCES Company(Id) ON DELETE CASCADE,
    Stamp TIMESTAMPTZ NOT NULL DEFAULT NOW()            
);