### AddAppToShelf
POST https://localhost:5001/app/shelf?releaseuid=YetAnotherImageProcessor_rel_001
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InJvb3QiLCJzdWIiOiJyb290IiwianRpIjoiOGMzYjI3ZjAyYzEyNGRmYzhiZDRkZGJkZDRmN2M1ODciLCJzaWQiOiJjZGRmMzJlM2M4MjQ0ZTNhYmI3MjkxZmEzODc1Zjk3YiIsImV4cCI6MTYwNTgwNTUxMiwiaXNzIjoid3V0LmJhbHRpY2xzYy5ldSIsImF1ZCI6Ind1dC5iYWx0aWNsc2MuZXUifQ.x0OjbAAh2buDpU9EeVYCno-UEyuq6g1jQMByYa-TYZc

### RemoveAppFromShelf
DELETE https://localhost:5001/app/shelf?releaseuid=YetAnotherImageProcessor_rel_001
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJycm9zemN6eWsiLCJlbWFpbCI6InJhZG9zbGF3LnJvc3pjenlrQGVlLnB3LmVkdS5wbCIsImp0aSI6IjhmMWY0MmMwLTQ2MjgtNGRhYS05ZDdiLTI1NmJjYzQ4MzNlZSIsImV4cCI6MTU5MTkxNDM1NywiaXNzIjoid3V0LmJhbHRpY2xzYy5ldSIsImF1ZCI6Ind1dC5iYWx0aWNsc2MuZXUifQ.uAZJn416MvhJxO8Uo78q0mpEwASqodVKtEvXCH00dGM

### GetShelfApps
GET https://localhost:5001/app/shelf
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InJvb3QiLCJzdWIiOiJyb290IiwianRpIjoiOGMzYjI3ZjAyYzEyNGRmYzhiZDRkZGJkZDRmN2M1ODciLCJzaWQiOiJjZGRmMzJlM2M4MjQ0ZTNhYmI3MjkxZmEzODc1Zjk3YiIsImV4cCI6MTYwNTgwNTUxMiwiaXNzIjoid3V0LmJhbHRpY2xzYy5ldSIsImF1ZCI6Ind1dC5iYWx0aWNsc2MuZXUifQ.x0OjbAAh2buDpU9EeVYCno-UEyuq6g1jQMByYa-TYZc

### FindApps
POST https://localhost:5001/app/list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJycm9zemN6eWsiLCJlbWFpbCI6InJhZG9zbGF3LnJvc3pjenlrQGVlLnB3LmVkdS5wbCIsImp0aSI6IjhmMWY0MmMwLTQ2MjgtNGRhYS05ZDdiLTI1NmJjYzQ4MzNlZSIsImV4cCI6MTU5MTkxNDM1NywiaXNzIjoid3V0LmJhbHRpY2xzYy5ldSIsImF1ZCI6Ind1dC5iYWx0aWNsc2MuZXUifQ.uAZJn416MvhJxO8Uo78q0mpEwASqodVKtEvXCH00dGM
Content-Type: application/json

{
  "onlyLastRelease": false
}

### FindAppReleases
POST https://localhost:5001/app/release/list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJycm9zemN6eWsiLCJlbWFpbCI6InJhZG9zbGF3LnJvc3pjenlrQGVlLnB3LmVkdS5wbCIsImp0aSI6IjhmMWY0MmMwLTQ2MjgtNGRhYS05ZDdiLTI1NmJjYzQ4MzNlZSIsImV4cCI6MTU5MTkxNDM1NywiaXNzIjoid3V0LmJhbHRpY2xzYy5ldSIsImF1ZCI6Ind1dC5iYWx0aWNsc2MuZXUifQ.uAZJn416MvhJxO8Uo78q0mpEwASqodVKtEvXCH00dGM
Content-Type: application/json

{
  "onlyLastRelease": false
}

### Portainer API
POST http://localhost:9000/api/endpoints/2/docker/containers/json?all=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGUiOjEsImV4cCI6MTYxMDc2OTg0NH0.gEXL-4wppGQ-9T2dR8TjO9gg0bbktvhD1h-tWl_Uk48