version: '3.7'

services:
  balticlsc-node:
    hostname: balticlsc-node
    image: balticlsc/balticlsc-node:local
    ports:
      - 7000:7000
      - 7001:7001
    networks:
      balticlsc-node:
        aliases:
          - balticlsc-node
          - balticlsc-node.balticlsc-node
#      balticlsc-batch-manager:
#        aliases:
#          - balticlsc-node
#          - balticlsc-node.balticlsc-batch-manager
#          - balticlsc-batch-manager
#          - balticlsc-batch-manager.balticlsc-batch-manager
    environment:
      masterHost: balticlsc-server
      masterPort: 5001
      nodePort: 7001
      clusterProxyUrl: https://cluster-proxy:6001
      clusterProjectName: balticlsc
      batchManagerUrl: https://balticlsc-node
      NodePublicHost: https://balticlsc-node:7001
    volumes:
      - type: bind
        source: ./logs/balticlsc-node
        target: /app/logs
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    logging:
      driver: fluentd
      options:
        tag: balticlsc-node
  
  cluster-proxy-swarm:
    hostname: cluster-proxy
    image: balticlsc/balticlsc-cluster-proxy-swarm:local
    ports: 
      - 6000:6000
      - 6001:6001
    networks:
      balticlsc-node:
        aliases:
         - cluster-proxy
         - cluster-proxy.balticlsc-node
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - type: bind
        source: ./logs/cluster-proxy-swarm
        target: /app/logs
    environment:
      projectPrefix: balticlsc
      batchManagerNetworkName: batch-manager
      portainerUsername: admin
      portainerPassword: adminadmin
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    logging:
      driver: fluentd
      options:
        tag: cluster-proxy-swarm
      

networks:
  balticlsc-server:
    external: true
 # balticlsc-batch-manager:
 #   external: true
  balticlsc-node:
    external: true
