version: '3.7'
services:
  fluentbit:
    image: fluentd:gelf
    networks:
      - balticlsc-logging
    ports:
      - 24224:24224
      - 5140:5140
    deploy:
      mode: global

  mongo:
    image: mongo:4.2
    networks:
      - balticlsc-logging

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.0
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1g
    networks:
      - balticlsc-logging
  
  graylog:
    image: graylog/graylog:4.0.2-2
    environment:
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_BIND_ADDRESS=0.0.0.0:8900
      - GRAYLOG_HTTP_EXTERNAL_URI=http://localhost:8900/
    networks:
      - balticlsc-logging
    ports:
      # Graylog web interface and REST API
      - 8900:8900
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp

networks:
  balticlsc-logging:
    external: true
    