version: '3.7'

services:
  simple-vis:
    hostname: simple-vis
    image: dockersamples/visualizer
    ports:
      - 8181:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CTX_ROOT=/visualizer
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
